[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "NetQIR"
authors = [{name = "Jorge Vázquez-Pérez", email = "jorgevazquez.perez@usc.es"}, {name = "F. Javier Cardama", email = "javier.cardama@usc.es"}]
dynamic = ["version", "description"]
